/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Category, Project, Photograph, CategoryDetails, ProjectDetails } from './types';

export const CATEGORIES_INFO: Record<Category, CategoryDetails> = {
  [Category.Landscape]: {
    id: Category.Landscape,
    nameZh: '风光摄影',
    nameEn: 'Landscape',
    intro: '观照自然纯粹本质，捕捉山川河流在静默流时中的季节低语与光影变迁。',
  },
  [Category.Documentary]: {
    id: Category.Documentary,
    nameZh: '纪实摄影',
    nameEn: 'Documentary',
    intro: '以克制的人文视角记录日常温存、街头偶发瞬间与时代消逝的生活微雕。',
  },
  [Category.Creative]: {
    id: Category.Creative,
    nameZh: '创意摄影',
    nameEn: 'Creative',
    intro: '解构现实三维空间，通过抽象色块、明暗重构及主观情感实验重塑视觉秩序。',
  },
  [Category.NewTopographics]: {
    id: Category.NewTopographics,
    nameZh: '新地形摄影',
    nameEn: 'New Topographics',
    intro: '冷静凝视人类活动对地表景观之改造，探究人工几何秩序与自然蛮荒力之共存张力。',
  },
};

export const PROJECTS_INFO: Record<Project, ProjectDetails> = {
  [Project.OldTowns]: {
    id: Project.OldTowns,
    nameZh: '老乡镇',
    nameEn: 'Old Towns & Vernaculars',
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    duration: '2021 – 2024',
    intro: '用镜头为老乡镇留存底片。老街的裂痕、老宅的烟火，都是渝北回望来路的坐标——为这座城市守住一份有温度的视觉记忆。',
    background: '最近我考虑了许久，决定启动一个长期摄影项目，名字就叫《此地》。拍摄和收集关于重庆渝北的照片，不一定是名胜景点，更多的是构成日常的片段。如果你也生活在这里，手机里存着觉得有意义的随手拍（一条街、一碗面、一片天…），欢迎发给我。若被选用，会署上你的名字，一起收进这个集子里。',
  },
  [Project.NewVillages]: {
    id: Project.NewVillages,
    nameZh: '新农村',
    nameEn: 'Modernizing Countryside',
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    duration: '2023 – 2026',
    intro: '聚焦现代化改造进程中的新乡村风貌。整齐的白色组屋、网格化良田，以及传统农民在新空间中所呈现出的适应与张力。',
    background: '在中国乡村振兴背景下，传统的无规则聚落瞬间转变为高效的网格化住宅及大面积机械化农场。这不仅是空间景观上的巨变，更是数千年来地缘、血缘关系的深层重组。照片采用冷峻的中画幅色调表达这种转型期的利落与生涩。',
  },
  [Project.UrbanBorders]: {
    id: Project.UrbanBorders,
    nameZh: '城市边缘发展',
    nameEn: 'Urban Edges & Transitions',
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    duration: '2022 – 2026',
    intro: '探索城乡结合地带之混沌空间。大吊车、未铺设的黄泥路、赫然矗立的精装样板房孤岛，勾勒出狂飙的城市扩张。',
    background: '城乡结合部的过渡带是一个充满活力又极具戏剧荒诞色彩的边缘磁场。农作物在巨型高架铁路下顽强生长，旧村落的废墟与玻璃幕墙新地标遥遥对望。这些景观构成了一幅幅关于“发展”这台庞大机器在土地上刻写的草稿。',
  },
};

export const PHOTOGRAPHS: Photograph[] = [
  // Wind / Landscapes
  {
    id: 'l1',
    title: 'Malin River Grand Waterfall',
    desc: '黑白影调里，瀑布从山间倾泻而下，带着朦胧的水汽',
    category: Category.NewTopographics,
    location: '贵州, 黔西南州兴义市 (Gui Zhou, Xin Yi)',
    year: 2025,
    imageUrl: '/images/1000012272.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '10s at f/8, ISO 100',
      focalLength: '24mm',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'l2',
    title: 'Drawing a Tree',
    desc: '竖线条的树干被拉成了流动的丝絮',
    category: Category.NewTopographics,
    location: '重庆, 南岸 (Chong Qing, Nan An)',
    year: 2025,
    imageUrl: '/images/1000030530 (3).webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/15s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 32MP',
    },
  },
  {
    id: 'l3',
    title: 'Flowers in Water Glass',
    desc: '水珠像放大镜，把后面的小雏菊都印在了自己身上，像藏了一整片花田',
    category: Category.Documentary,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/1000030664.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/4.0, ISO 200',
      focalLength: '70mm',
      format: 'Medium Format 32MP',
    },
  },

  // Documentary / 人文
  {
    id: 'd1',
    title: 'Flowers in Water Glass',
    desc: '水珠像放大镜，把后面的小雏菊都印在了自己身上，像藏了一整片花田',
    category: Category.NewTopographics,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/1000030665.webp',
    aspectRatio: '3:4',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/4.0, ISO 200',
      focalLength: '70mm',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'd2',
    title: 'Tree and Reflection',
    desc: '横斜的苍劲树枝探向水面，满屏鲜绿的树叶透着柔光',
    category: Category.NewTopographics,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/1000030995.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '28mm',
      format: 'Full Frame 32MP',
    },
  },
  {
    id: 'd3',
    title: 'Rider of Light',
    desc: '骑行在光影之下',
    category: Category.NewTopographics,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/1738407238184 (1).webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 32MP',
    },
  },

  // Creative / 创意重构
  {
    id: 'c2',
    title: 'Light and Shadow Fantasy',
    desc: '血红般，如同虚幻，有点戏剧性色彩',
    category: Category.Creative,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/未标题-7-3.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/10s at f/8, ISO 100',
      focalLength: '35mm',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'c3',
    title: 'Triangular stability',
    desc: '仰拍秋日暖调树林，鲜亮治愈',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/1960512724.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm Studio Macro',
      format: 'Full Frame 32MP',
    },
  },

  // New Topographics / 新地形
  {
    id: 'nt1',
    title: 'Hill',
    desc: '翠网覆丘，林影环围，野趣藏于静处',
    category: Category.NewTopographics,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR08860.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '55mm',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'nt2',
    title: 'Distant Road',
    desc: '通往远方的路，破碎的草坪',
    category: Category.NewTopographics,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00432.webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '24mm Ultra-Wide',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'nt3',
    title: 'After the year',
    desc: '红色的爆竹碎屑，通往回家的路',
    category: Category.NewTopographics,
    project: Project.UrbanBorders,
    location: '重庆, 北碚 (Chong Qing, Bei Bei)',
    year: 2025,
    imageUrl: '/images/ZTR08301.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 32MP',
    },
  },

  // Regional Project: New Villages
  {
    id: 'nv1',
    title: 'Who is tall?',
    desc: '墙，草，杆',
    category: Category.NewTopographics,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR08152.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 100',
      focalLength: '38mm Wide-Angle',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'nv2',
    title: 'Round ball',
    desc: '堆栈出来的植物跟原本大不一样，像画',
    category: Category.NewTopographics,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/2111_1.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '24mm Wide',
      format: 'Full Frame 32MP',
    },
  },
  {
    id: 'nv3',
    title: 'Shed',
    desc: '远处的大桥静静的，近处江河流动',
    category: Category.NewTopographics,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00368-3.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '30mm',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'l4',
    title: "People's Great Hall",
    desc: '大礼堂庄严漂亮',
    category: Category.Creative,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC00278.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '24mm',
      format: 'Medium Format 32MP',
    },
  },
  {
    id: 'l5',
    title: 'Dead tree',
    desc: '天黑之前在鹿山公园闲逛，拍下了这颗枯树',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC00330 (1).webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 32MP',
    },
  },
  {
    id: 'l6',
    title: '',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC00278.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '24mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'l7',
    title: 'Dune Meridian',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR07739.webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '38mm',
      format: 'Medium Format 100MP',
    },
  },
  {
    id: 'l8',
    title: 'Tidal Canvas',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC01257.webp',
    aspectRatio: '3:4',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'l9',
    title: 'Alpine Bloom',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/1960512724.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'l10',
    title: 'Canyon Veil',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/设计工程学院2025级风景园林五班周亭燃1.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '55mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'l11',
    title: 'Volcanic Solitude',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR08404.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '100mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'lnv1',
    title: 'Terraced Renewal',
    desc: '',
    category: Category.Creative,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC01864 (1).webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '45mm',
      format: 'Medium Format 100MP',
    },
  },
  {
    id: 'lnv2',
    title: 'Valley Settlement',
    desc: '',
    category: Category.Landscape,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/设计工程学院2025级风景园林五班周亭燃3.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '65mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'lnv3',
    title: 'Greenhouse Horizon',
    desc: '',
    category: Category.NewTopographics,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC01869 (3).webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'lnv4',
    title: 'Agrarian Grid',
    desc: '',
    category: Category.NewTopographics,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC01950 (1).webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '18mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'd4',
    title: 'Alleyway Echoes',
    desc: '',
    category: Category.Creative,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSC02003.webp',
    aspectRatio: '3:4',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '28mm',
      format: '35mm HP5 Plus Black & White Film',
    },
  },
  {
    id: 'd5',
    title: 'Silk Weaver\'s Hands',
    desc: '',
    category: Category.Creative,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/DSCF1114-01.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '28mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'd6',
    title: 'Riverside Laundry',
    desc: '',
    category: Category.Documentary,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR08157.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'd7',
    title: 'Doorway Portrait',
    desc: '',
    category: Category.Creative,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/Image_1718808473663 (1).webp',
    aspectRatio: '1:1',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'd8',
    title: 'Temple Fair',
    desc: '',
    category: Category.NewTopographics,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_20250203_205655.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'd9',
    title: 'Old Bridge Passage',
    desc: '',
    category: Category.Landscape,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_20250801_154257.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'd10',
    title: 'Iron Forge',
    desc: '',
    category: Category.NewTopographics,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_20250807_153458.webp',
    aspectRatio: '3:4',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: '35mm Tri-X Black & White Film',
    },
  },
  {
    id: 'd12',
    title: 'Apothecary Shelf',
    desc: '',
    category: Category.Landscape,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_3330 (1).webp',
    aspectRatio: '1:1',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '80mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'd13',
    title: 'Lantern Night',
    desc: '',
    category: Category.NewTopographics,
    project: Project.OldTowns,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_3478.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '28mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'd14',
    title: 'Departure Gate',
    desc: '',
    category: Category.Creative,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_3697 (2).webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'd15',
    title: 'Lunch Break',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_4428.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'd16',
    title: 'Street Flavor',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/quality_restoration_20240602104349615_1.webp',
    aspectRatio: '3:4',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '85mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'd17',
    title: 'Dawn Catch',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/retouch_2024060120044808 (1).webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '135mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'd18',
    title: 'Village Classroom',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/retouch_2024060918051690 (1).webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '28mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'dnv1',
    title: 'Community Center',
    desc: '',
    category: Category.Landscape,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/retouch_2024061014022519.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'dnv2',
    title: 'Drone Farmer',
    desc: '',
    category: Category.Landscape,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00304.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'dnv3',
    title: 'New Home',
    desc: '',
    category: Category.Landscape,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00344-4.webp',
    aspectRatio: '1:1',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '28mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'c4',
    title: 'Prism Scatter',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00350.webp',
    aspectRatio: '1:1',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '55mm',
      format: 'Medium Format 50MP',
    },
  },
  {
    id: 'c5',
    title: 'Shadow Lattice',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00359.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '110mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'c6',
    title: 'Surface Tension',
    desc: '',
    category: Category.Documentary,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00368-3.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '90mm Macro',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'c7',
    title: 'Double Exposure Grove',
    desc: '',
    category: Category.Documentary,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00377.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'c8',
    title: 'Neon Rain',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00389-2.webp',
    aspectRatio: '1:1',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'c9',
    title: 'Fabric Wave',
    desc: '',
    category: Category.Documentary,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00400-2.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '90mm',
      format: 'Medium Format 100MP',
    },
  },
  {
    id: 'c10',
    title: 'Smoke Trajectory',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00406.webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '90mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'c11',
    title: 'Fragment Mirror',
    desc: '',
    category: Category.Creative,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/1000030530 (3).webp',
    aspectRatio: '1:1',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '63mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'c12',
    title: 'Ink Diffusion',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00418.webp',
    aspectRatio: '3:4',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '100mm Macro',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'c13',
    title: 'Steel Abstraction',
    desc: '',
    category: Category.Creative,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/quality_restoration_20240602104349615_1.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '200mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'c14',
    title: 'Motion Blur Avenue',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00421.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'c15',
    title: 'Spectrum Crystal',
    desc: '',
    category: Category.Creative,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/IMG_4428.webp',
    aspectRatio: '1:1',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '55mm',
      format: 'Medium Format 50MP',
    },
  },
  {
    id: 'nt5',
    title: '',
    desc: '',
    category: Category.Creative,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00432.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '21mm',
      format: 'Medium Format 100MP',
    },
  },
  {
    id: 'nt6',
    title: '',
    desc: '',
    category: Category.Landscape,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00472.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'nt7',
    title: '',
    desc: '',
    category: Category.Documentary,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00473.webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '24mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'nt8',
    title: '',
    desc: '',
    category: Category.NewTopographics,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR04432.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'nt9',
    title: '',
    desc: '',
    category: Category.NewTopographics,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00344-4.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'nt10',
    title: '',
    desc: '',
    category: Category.Landscape,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00476.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '30mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'nt11',
    title: '',
    desc: '',
    category: Category.Landscape,
    project: Project.UrbanBorders,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00491-3.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '38mm',
      format: 'Medium Format 100MP',
    },
  },
  {
    id: 'ntv1',
    title: '',
    desc: '',
    category: Category.Landscape,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00514.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '45mm',
      format: 'Medium Format 100MP',
    },
  },
  {
    id: 'ntv2',
    title: '',
    desc: '',
    category: Category.Creative,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00519-2.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '45mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'ntv3',
    title: '',
    desc: '',
    category: Category.NewTopographics,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00609.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'ntv4',
    title: '',
    desc: '',
    category: Category.Creative,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00560.webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '18mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'ntv5',
    title: '',
    desc: '',
    category: Category.NewTopographics,
    project: Project.NewVillages,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR06912.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 45MP',
    },
  },
  {
    id: 'nt12',
    title: '',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00406.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '38mm',
      format: 'Medium Format 100MP',
    },
  },
  {
    id: 'nt13',
    title: '',
    desc: '',
    category: Category.NewTopographics,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR07182.webp',
    aspectRatio: '4:3',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '23mm',
      format: 'Medium Format 102MP',
    },
  },
  {
    id: 'nt14',
    title: '',
    desc: '',
    category: Category.Documentary,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00571.webp',
    aspectRatio: '3:2',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '50mm',
      format: 'Full Frame 60MP',
    },
  },
  {
    id: 'nt15',
    title: '',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00588.webp',
    aspectRatio: '16:10',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '100mm',
      format: 'Full Frame 61MP',
    },
  },
  {
    id: 'nt16',
    title: '',
    desc: '',
    category: Category.Landscape,
    location: '重庆, 渝北 (Chong Qing, Yu Bei)',
    year: 2025,
    imageUrl: '/images/ZTR00591.webp',
    aspectRatio: '16:9',
    exif: {
      camera: 'Sony A7M4',
      lens: 'FE 24-70mm f/2.8 GM II',
      exposure: '1/125s at f/8, ISO 200',
      focalLength: '35mm',
      format: 'Full Frame 45MP',
    },
  }
];
