import { Photograph } from './types';

export const PHOTOGRAPHS: Photograph[] = [
  {
    id: 'img1',
    title: 'Center Line / 中线',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/中线.webp',
      originalJpgUrl: '/images/摄影图片总集/中线.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img2',
    title: 'Construction / 建',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/建 .webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img3',
    title: 'Construction No.4 / 建 No.4',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/建 No.4.webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img4',
    title: 'Construction / 建',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/建.webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img5',
    title: 'Breaking Through the Wall / 破墙而出',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/破墙而出.webp',
      originalJpgUrl: '/images/摄影图片总集/破墙而出.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img6',
    title: 'Green Grass / 绿皮草',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/绿皮草.webp',
      originalJpgUrl: '/images/摄影图片总集/绿皮草.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img7',
    title: 'Passage No.4 / 通道 No.4',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道 No.4.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.4.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img8',
    title: 'Passage No.5 / 通道 No.5',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道 No.5.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.5.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img9',
    title: 'Passage No.6 / 通道 No.6',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道 No.6.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.6.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img10',
    title: 'Passage / 通道',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道.webp',
      originalJpgUrl: '/images/摄影图片总集/通道.jpg',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img11',
    title: 'Construction No.3 / 建 No.3',
    desc: '',
    imageUrl: '/images/专题-新农村/建 No.3.webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: null,
    project: 'new-villages',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img12',
    title: 'Mirror / 镜',
    desc: '',
    imageUrl: '/images/专题-新农村/镜.webp',
      originalJpgUrl: '/images/摄影图片总集/镜.jpg',
    category: null,
    project: 'new-villages',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img13',
    title: 'Triangle No.3 / 三角 No.3',
    desc: '',
    imageUrl: '/images/专题-老乡镇/三角 No.3.webp',
      originalJpgUrl: '/images/摄影图片总集/三角 No.3.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img14',
    title: 'Farm Tools No.2 / 农具 No.2',
    desc: '',
    imageUrl: '/images/专题-老乡镇/农具 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/农具 No.2.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img15',
    title: 'Farm Tools / 农具',
    desc: '',
    imageUrl: '/images/专题-老乡镇/农具.webp',
      originalJpgUrl: '/images/摄影图片总集/农具.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img16',
    title: 'After New Year / 年后',
    desc: '',
    imageUrl: '/images/专题-老乡镇/年后.webp',
      originalJpgUrl: '/images/摄影图片总集/年后.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img17',
    title: 'Extension / 延伸',
    desc: '',
    imageUrl: '/images/专题-老乡镇/延伸.webp',
      originalJpgUrl: '/images/摄影图片总集/延伸.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img18',
    title: 'Playing with Water / 戏水',
    desc: '',
    imageUrl: '/images/专题-老乡镇/戏水.webp',
      originalJpgUrl: '/images/摄影图片总集/戏水.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img19',
    title: 'Looking Towards / 望向',
    desc: '',
    imageUrl: '/images/专题-老乡镇/望向.webp',
      originalJpgUrl: '/images/摄影图片总集/望向.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img20',
    title: 'Broken Mirror / 破镜',
    desc: '',
    imageUrl: '/images/专题-老乡镇/破镜.webp',
      originalJpgUrl: '/images/摄影图片总集/破镜.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img21',
    title: 'Stability / 稳定',
    desc: '',
    imageUrl: '/images/专题-老乡镇/稳定.webp',
      originalJpgUrl: '/images/摄影图片总集/稳定.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img22',
    title: 'Door / 门',
    desc: '',
    imageUrl: '/images/专题-老乡镇/门.webp',
      originalJpgUrl: '/images/摄影图片总集/门.jpg',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img23',
    title: 'Light and Sound / 光音',
    desc: '',
    imageUrl: '/images/创意摄影/光音.webp',
      originalJpgUrl: '/images/摄影图片总集/光音.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img24',
    title: 'Guitar Close-up / 吉他特写',
    desc: '',
    imageUrl: '/images/创意摄影/吉他特写.webp',
      originalJpgUrl: '/images/摄影图片总集/吉他特写.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img25',
    title: 'Running Towards Light / 向光跑',
    desc: '',
    imageUrl: '/images/创意摄影/向光跑.webp',
      originalJpgUrl: '/images/摄影图片总集/向光跑.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img26',
    title: 'Phantom / 幻影',
    desc: '',
    imageUrl: '/images/创意摄影/幻影.webp',
      originalJpgUrl: '/images/摄影图片总集/幻影.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img27',
    title: 'Tree Form / 树型',
    desc: '',
    imageUrl: '/images/创意摄影/树型.webp',
      originalJpgUrl: '/images/摄影图片总集/树型.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img28',
    title: 'Cherry Blossom Reconstruction / 樱花重组',
    desc: '',
    imageUrl: '/images/创意摄影/樱花重组.webp',
      originalJpgUrl: '/images/摄影图片总集/樱花重组.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img29',
    title: 'Oil Flower / 油花',
    desc: '',
    imageUrl: '/images/创意摄影/油花.webp',
      originalJpgUrl: '/images/摄影图片总集/油花.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img30',
    title: 'Vitality / 生机',
    desc: '',
    imageUrl: '/images/创意摄影/生机.webp',
      originalJpgUrl: '/images/摄影图片总集/生机.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img31',
    title: 'Rouge Red No.2 / 胭脂红 No.2',
    desc: '',
    imageUrl: '/images/创意摄影/胭脂红 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/胭脂红 No.2.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img32',
    title: 'Rouge Red / 胭脂红',
    desc: '',
    imageUrl: '/images/创意摄影/胭脂红.webp',
      originalJpgUrl: '/images/摄影图片总集/胭脂红.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img33',
    title: 'Dance, Run / 舞，跑',
    desc: '',
    imageUrl: '/images/创意摄影/舞，跑.webp',
      originalJpgUrl: '/images/摄影图片总集/舞，跑.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img34',
    title: 'Glow / 辉光',
    desc: '',
    imageUrl: '/images/创意摄影/辉光.webp',
      originalJpgUrl: '/images/摄影图片总集/辉光.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img35',
    title: 'Reconstruction / 重构',
    desc: '',
    imageUrl: '/images/创意摄影/重构.webp',
      originalJpgUrl: '/images/摄影图片总集/重构.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img36',
    title: 'Splash / 飞溅',
    desc: '',
    imageUrl: '/images/创意摄影/飞溅.webp',
      originalJpgUrl: '/images/摄影图片总集/飞溅.jpg',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img37',
    title: 'Center Line No.2 / 中线 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/中线 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/中线 No.2.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img38',
    title: 'Center Line / 中线',
    desc: '',
    imageUrl: '/images/新地形摄影/中线.webp',
      originalJpgUrl: '/images/摄影图片总集/中线.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img39',
    title: 'Human, Center / 人，中心',
    desc: '',
    imageUrl: '/images/新地形摄影/人，中心.webp',
      originalJpgUrl: '/images/摄影图片总集/人，中心.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img40',
    title: 'Rockery / 假山',
    desc: '',
    imageUrl: '/images/新地形摄影/假山.webp',
      originalJpgUrl: '/images/摄影图片总集/假山.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img41',
    title: 'Logarithm No.2 / 对数 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/对数 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/对数 No.2.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img42',
    title: 'Logarithm / 对数',
    desc: '',
    imageUrl: '/images/新地形摄影/对数.webp',
      originalJpgUrl: '/images/摄影图片总集/对数.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img43',
    title: 'Construction / 建',
    desc: '',
    imageUrl: '/images/新地形摄影/建 .webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img44',
    title: 'Construction No.4 / 建 No.4',
    desc: '',
    imageUrl: '/images/新地形摄影/建 No.4.webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img45',
    title: 'Construction / 建',
    desc: '',
    imageUrl: '/images/新地形摄影/建.webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img46',
    title: 'Expansion / 扩张',
    desc: '',
    imageUrl: '/images/新地形摄影/扩张.webp',
      originalJpgUrl: '/images/摄影图片总集/扩张.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img47',
    title: 'Stranded / 搁浅',
    desc: '',
    imageUrl: '/images/新地形摄影/搁浅.webp',
      originalJpgUrl: '/images/摄影图片总集/搁浅.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img48',
    title: 'Curve / 曲线',
    desc: '',
    imageUrl: '/images/新地形摄影/曲线.webp',
      originalJpgUrl: '/images/摄影图片总集/曲线.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img49',
    title: 'Withered / 枯',
    desc: '',
    imageUrl: '/images/新地形摄影/枯.webp',
      originalJpgUrl: '/images/摄影图片总集/枯.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img50',
    title: 'River, Bridge, Shed / 江，桥，棚',
    desc: '',
    imageUrl: '/images/新地形摄影/江，桥，棚.webp',
      originalJpgUrl: '/images/摄影图片总集/江，桥，棚.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img51',
    title: 'Shallow Beach / 浅滩',
    desc: '',
    imageUrl: '/images/新地形摄影/浅滩.webp',
      originalJpgUrl: '/images/摄影图片总集/浅滩.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img52',
    title: 'Field / 田',
    desc: '',
    imageUrl: '/images/新地形摄影/田.webp',
      originalJpgUrl: '/images/摄影图片总集/田.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img53',
    title: 'Breaking Through the Wall / 破墙而出',
    desc: '',
    imageUrl: '/images/新地形摄影/破墙而出.webp',
      originalJpgUrl: '/images/摄影图片总集/破墙而出.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img54',
    title: 'Childhood No.2 / 童年 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/童年 No.2 .webp',
      originalJpgUrl: '/images/摄影图片总集/童年 No.2 .jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img55',
    title: 'Childhood / 童年',
    desc: '',
    imageUrl: '/images/新地形摄影/童年.webp',
      originalJpgUrl: '/images/摄影图片总集/童年.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img56',
    title: 'Green Grass / 绿皮草',
    desc: '',
    imageUrl: '/images/新地形摄影/绿皮草.webp',
      originalJpgUrl: '/images/摄影图片总集/绿皮草.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img57',
    title: 'Green Curtain / 绿色围布',
    desc: '',
    imageUrl: '/images/新地形摄影/绿色围布.webp',
      originalJpgUrl: '/images/摄影图片总集/绿色围布.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img58',
    title: 'Fiction / 虚构',
    desc: '',
    imageUrl: '/images/新地形摄影/虚构.webp',
      originalJpgUrl: '/images/摄影图片总集/虚构.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img59',
    title: 'Crack / 裂痕',
    desc: '',
    imageUrl: '/images/新地形摄影/裂痕.webp',
      originalJpgUrl: '/images/摄影图片总集/裂痕.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img60',
    title: 'Who is Higher? / 谁高？',
    desc: '',
    imageUrl: '/images/新地形摄影/谁高？.webp',
      originalJpgUrl: '/images/摄影图片总集/谁高？.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img61',
    title: 'Passage No.2 / 通道 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.2.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img62',
    title: 'Passage No.3 / 通道 No.3',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.3.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.3.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img63',
    title: 'Passage No.4 / 通道 No.4',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.4.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.4.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img64',
    title: 'Passage No.5 / 通道 No.5',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.5.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.5.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img65',
    title: 'Passage No.6 / 通道 No.6',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.6.webp',
      originalJpgUrl: '/images/摄影图片总集/通道 No.6.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img66',
    title: 'Passage / 通道',
    desc: '',
    imageUrl: '/images/新地形摄影/通道.webp',
      originalJpgUrl: '/images/摄影图片总集/通道.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img67',
    title: 'Door / 门',
    desc: '',
    imageUrl: '/images/新地形摄影/门.webp',
      originalJpgUrl: '/images/摄影图片总集/门.jpg',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img68',
    title: 'Triangle No.3 / 三角 No.3',
    desc: '',
    imageUrl: '/images/纪实摄影/三角 No.3.webp',
      originalJpgUrl: '/images/摄影图片总集/三角 No.3.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img69',
    title: 'Farm Tools No.2 / 农具 No.2',
    desc: '',
    imageUrl: '/images/纪实摄影/农具 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/农具 No.2.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img70',
    title: 'Farm Tools / 农具',
    desc: '',
    imageUrl: '/images/纪实摄影/农具.webp',
      originalJpgUrl: '/images/摄影图片总集/农具.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img71',
    title: 'Labor / 劳作',
    desc: '',
    imageUrl: '/images/纪实摄影/劳作.webp',
      originalJpgUrl: '/images/摄影图片总集/劳作.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img72',
    title: 'Four Grid / 四宫格',
    desc: '',
    imageUrl: '/images/纪实摄影/四宫格.webp',
      originalJpgUrl: '/images/摄影图片总集/四宫格.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img73',
    title: 'Pile / 堆',
    desc: '',
    imageUrl: '/images/纪实摄影/堆.webp',
      originalJpgUrl: '/images/摄影图片总集/堆.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img74',
    title: 'After New Year / 年后',
    desc: '',
    imageUrl: '/images/纪实摄影/年后.webp',
      originalJpgUrl: '/images/摄影图片总集/年后.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img75',
    title: 'Extension / 延伸',
    desc: '',
    imageUrl: '/images/纪实摄影/延伸.webp',
      originalJpgUrl: '/images/摄影图片总集/延伸.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img76',
    title: 'Construction No.3 / 建 No.3',
    desc: '',
    imageUrl: '/images/纪实摄影/建 No.3.webp',
      originalJpgUrl: '/images/摄影图片总集/建.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img77',
    title: 'Shadow / 影',
    desc: '',
    imageUrl: '/images/纪实摄影/影 .webp',
      originalJpgUrl: '/images/摄影图片总集/影 .jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img78',
    title: 'Shadow No.2 / 影 No.2',
    desc: '',
    imageUrl: '/images/纪实摄影/影 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/影 .jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img79',
    title: 'Playing with Water / 戏水',
    desc: '',
    imageUrl: '/images/纪实摄影/戏水.webp',
      originalJpgUrl: '/images/摄影图片总集/戏水.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img80',
    title: 'Looking Towards / 望向',
    desc: '',
    imageUrl: '/images/纪实摄影/望向.webp',
      originalJpgUrl: '/images/摄影图片总集/望向.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img81',
    title: 'Ashes / 灰烬',
    desc: '',
    imageUrl: '/images/纪实摄影/灰烬.webp',
      originalJpgUrl: '/images/摄影图片总集/灰烬.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img82',
    title: 'Focus / 焦点',
    desc: '',
    imageUrl: '/images/纪实摄影/焦点.webp',
      originalJpgUrl: '/images/摄影图片总集/焦点.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img83',
    title: 'Dog Footprints / 狗脚印',
    desc: '',
    imageUrl: '/images/纪实摄影/狗脚印.webp',
      originalJpgUrl: '/images/摄影图片总集/狗脚印.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img84',
    title: 'Rupture / 破裂',
    desc: '',
    imageUrl: '/images/纪实摄影/破裂.webp',
      originalJpgUrl: '/images/摄影图片总集/破裂.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img85',
    title: 'Broken Mirror / 破镜',
    desc: '',
    imageUrl: '/images/纪实摄影/破镜.webp',
      originalJpgUrl: '/images/摄影图片总集/破镜.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img86',
    title: 'Stability / 稳定',
    desc: '',
    imageUrl: '/images/纪实摄影/稳定.webp',
      originalJpgUrl: '/images/摄影图片总集/稳定.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img87',
    title: 'Waiting / 等待',
    desc: '',
    imageUrl: '/images/纪实摄影/等待.webp',
      originalJpgUrl: '/images/摄影图片总集/等待.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img88',
    title: 'Step / 踏',
    desc: '',
    imageUrl: '/images/纪实摄影/踏.webp',
      originalJpgUrl: '/images/摄影图片总集/踏.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img89',
    title: 'Car Wall / 车墙',
    desc: '',
    imageUrl: '/images/纪实摄影/车墙.webp',
      originalJpgUrl: '/images/摄影图片总集/车墙.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img90',
    title: 'Connection No.2 / 连接 No.2',
    desc: '',
    imageUrl: '/images/纪实摄影/连接 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/连接 No.2.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img91',
    title: 'Connection No.3 / 连接 No.3',
    desc: '',
    imageUrl: '/images/纪实摄影/连接 No.3.webp',
      originalJpgUrl: '/images/摄影图片总集/连接 No.3.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img92',
    title: 'Connection / 连接',
    desc: '',
    imageUrl: '/images/纪实摄影/连接.webp',
      originalJpgUrl: '/images/摄影图片总集/连接.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img93',
    title: 'Encounter / 遇见',
    desc: '',
    imageUrl: '/images/纪实摄影/遇见.webp',
      originalJpgUrl: '/images/摄影图片总集/遇见.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img94',
    title: 'Mirror / 镜',
    desc: '',
    imageUrl: '/images/纪实摄影/镜.webp',
      originalJpgUrl: '/images/摄影图片总集/镜.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img95',
    title: 'Sunlight Rider / 阳光骑者',
    desc: '',
    imageUrl: '/images/纪实摄影/阳光骑者.webp',
      originalJpgUrl: '/images/摄影图片总集/阳光骑者.jpg',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img96',
    title: 'Lights of Ten Thousand Homes / 万家灯火',
    desc: '',
    imageUrl: '/images/风光摄影/万家灯火.webp',
      originalJpgUrl: '/images/摄影图片总集/万家灯火.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img97',
    title: 'Triangle No.2 / 三角 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/三角 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/三角 No.2.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img98',
    title: 'Triangle No.4 / 三角 No.4',
    desc: '',
    imageUrl: '/images/风光摄影/三角 No.4.webp',
      originalJpgUrl: '/images/摄影图片总集/三角 No.4.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img99',
    title: 'Triangle / 三角',
    desc: '',
    imageUrl: '/images/风光摄影/三角.webp',
      originalJpgUrl: '/images/摄影图片总集/三角.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img100',
    title: 'Interweave No.2 / 交织 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/交织 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/交织 No.2.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img101',
    title: 'Interweave / 交织',
    desc: '',
    imageUrl: '/images/风光摄影/交织.webp',
      originalJpgUrl: '/images/摄影图片总集/交织.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img102',
    title: '千厮门',
    desc: '',
    imageUrl: '/images/风光摄影/千厮门.webp',
      originalJpgUrl: '/images/摄影图片总集/千厮门.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img103',
    title: '单枝',
    desc: '',
    imageUrl: '/images/风光摄影/单枝.webp',
      originalJpgUrl: '/images/摄影图片总集/单枝.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img104',
    title: '向上',
    desc: '',
    imageUrl: '/images/风光摄影/向上.webp',
      originalJpgUrl: '/images/摄影图片总集/向上.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img105',
    title: '大礼堂',
    desc: '',
    imageUrl: '/images/风光摄影/大礼堂.webp',
      originalJpgUrl: '/images/摄影图片总集/大礼堂.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img106',
    title: '奔腾',
    desc: '',
    imageUrl: '/images/风光摄影/奔腾.webp',
      originalJpgUrl: '/images/摄影图片总集/奔腾.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img107',
    title: '山间',
    desc: '',
    imageUrl: '/images/风光摄影/山间.webp',
      originalJpgUrl: '/images/摄影图片总集/山间.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img108',
    title: '干',
    desc: '',
    imageUrl: '/images/风光摄影/干.webp',
      originalJpgUrl: '/images/摄影图片总集/干.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img109',
    title: '日照',
    desc: '',
    imageUrl: '/images/风光摄影/日照.webp',
      originalJpgUrl: '/images/摄影图片总集/日照.jpeg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img110',
    title: '春 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/春 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/春 No.2.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img111',
    title: '春',
    desc: '',
    imageUrl: '/images/风光摄影/春.webp',
      originalJpgUrl: '/images/摄影图片总集/春.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img112',
    title: 'Withered / 枯',
    desc: '',
    imageUrl: '/images/风光摄影/枯 .webp',
      originalJpgUrl: '/images/摄影图片总集/枯.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img113',
    title: '江夜',
    desc: '',
    imageUrl: '/images/风光摄影/江夜.webp',
      originalJpgUrl: '/images/摄影图片总集/江夜.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img114',
    title: '空枝 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/空枝 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/空枝 No.2.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img115',
    title: '空枝',
    desc: '',
    imageUrl: '/images/风光摄影/空枝.webp',
      originalJpgUrl: '/images/摄影图片总集/空枝.JPG',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img116',
    title: '绿草 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/绿草 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/绿草 No.2.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img117',
    title: '绿草',
    desc: '',
    imageUrl: '/images/风光摄影/绿草.webp',
      originalJpgUrl: '/images/摄影图片总集/绿草.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img118',
    title: '群山之中',
    desc: '',
    imageUrl: '/images/风光摄影/群山之中.webp',
      originalJpgUrl: '/images/摄影图片总集/群山之中.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img119',
    title: '花与蜜蜂',
    desc: '',
    imageUrl: '/images/风光摄影/花与蜜蜂.webp',
      originalJpgUrl: '/images/摄影图片总集/花与蜜蜂.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img120',
    title: '菜园坝与夜',
    desc: '',
    imageUrl: '/images/风光摄影/菜园坝与夜.webp',
      originalJpgUrl: '/images/摄影图片总集/菜园坝与夜.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img121',
    title: '蔡家大桥 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/蔡家大桥 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/蔡家大桥 No.2.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img122',
    title: '蔡家大桥 No.3',
    desc: '',
    imageUrl: '/images/风光摄影/蔡家大桥 No.3.webp',
      originalJpgUrl: '/images/摄影图片总集/蔡家大桥 No.3.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img123',
    title: '蔡家大桥',
    desc: '',
    imageUrl: '/images/风光摄影/蔡家大桥.webp',
      originalJpgUrl: '/images/摄影图片总集/蔡家大桥.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img124',
    title: '行者',
    desc: '',
    imageUrl: '/images/风光摄影/行者 .webp',
      originalJpgUrl: '/images/摄影图片总集/行者 .jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img125',
    title: '行者 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/行者 No.2.webp',
      originalJpgUrl: '/images/摄影图片总集/行者 .jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img126',
    title: '近草远桥',
    desc: '',
    imageUrl: '/images/风光摄影/近草远桥.webp',
      originalJpgUrl: '/images/摄影图片总集/近草远桥.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img127',
    title: '霓虹',
    desc: '',
    imageUrl: '/images/风光摄影/霓虹.webp',
      originalJpgUrl: '/images/摄影图片总集/霓虹.jpg',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
];
import { Category, Project } from './types';

export type CategoryInfo = {
  nameZh: string;
  nameEn: string;
  desc: string;
};

export type ProjectInfo = {
  nameZh: string;
  nameEn: string;
  intro: string;
  background: string;
  duration: string;
};

export const CATEGORIES_INFO: Record<Category, CategoryInfo> = {
  landscape: {
    nameZh: '风光摄影',
    nameEn: 'Landscape Photography',
    desc: '山川河流、日出日落、自然之美',
  },
  documentary: {
    nameZh: '纪实摄影',
    nameEn: 'Documentary Photography',
    desc: '街头巷尾、人文故事、生活瞬间',
  },
  creative: {
    nameZh: '创意摄影',
    nameEn: 'Creative Photography',
    desc: '光影实验、艺术表达、视觉探索',
  },
  'new-topographics': {
    nameZh: '新地形摄影',
    nameEn: 'New Topographics',
    desc: '人与自然、城市边缘、环境变迁',
  },
};

export const PROJECTS_INFO: Record<Project, ProjectInfo> = {
  'old-towns': {
    nameZh: '老乡镇',
    nameEn: 'Old Towns',
    intro: '记录那些即将消失的老乡镇，留住时光的痕迹',
    background: '重庆渝北区老乡镇纪实摄影项目',
    duration: '2025 - 2026',
  },
  'new-villages': {
    nameZh: '新农村',
    nameEn: 'New Villages',
    intro: '新农村建设中的变化与传承',
    background: '重庆渝北区新农村发展记录',
    duration: '2025 - 2026',
  },
  'urban-borders': {
    nameZh: '城市边缘发展',
    nameEn: 'Urban Borders',
    intro: '城市扩张与乡村边界的交汇地带',
    background: '重庆渝北区城市化进程记录',
    duration: '2025 - 2026',
  },
};
