import { Photograph, Video, VideoCategory, VideoCategoryDetails, Project } from './types';

export const PHOTOGRAPHS: Photograph[] = [
  {
    id: 'img1',
    title: '中线',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/中线.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img2',
    title: '建',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/建 .webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img3',
    title: '建 No.4 (1)',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/建 No.4 (1).webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img4',
    title: '建',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/建.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img5',
    title: '破墙而出',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/破墙而出.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img6',
    title: '绿皮草',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/绿皮草.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img7',
    title: '通道 No.4',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道 No.4.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img8',
    title: '通道 No.5',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道 No.5.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img9',
    title: '通道 No.6',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道 No.6.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img10',
    title: '通道',
    desc: '',
    imageUrl: '/images/专题-城市边缘发展/通道.webp',
    category: null,
    project: 'urban-borders',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img11',
    title: '建 No.3',
    desc: '',
    imageUrl: '/images/专题-新农村/建 No.3.webp',
    category: null,
    project: 'new-villages',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img12',
    title: '镜',
    desc: '',
    imageUrl: '/images/专题-新农村/镜.webp',
    category: null,
    project: 'new-villages',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img13',
    title: '三角 No.3',
    desc: '',
    imageUrl: '/images/专题-老乡镇/三角 No.3.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img14',
    title: '农具 No.2',
    desc: '',
    imageUrl: '/images/专题-老乡镇/农具 No.2.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img15',
    title: '农具',
    desc: '',
    imageUrl: '/images/专题-老乡镇/农具.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img16',
    title: '年后',
    desc: '',
    imageUrl: '/images/专题-老乡镇/年后.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img17',
    title: '延伸',
    desc: '',
    imageUrl: '/images/专题-老乡镇/延伸.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img18',
    title: '戏水',
    desc: '',
    imageUrl: '/images/专题-老乡镇/戏水.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img19',
    title: '望向',
    desc: '',
    imageUrl: '/images/专题-老乡镇/望向.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img20',
    title: '破镜',
    desc: '',
    imageUrl: '/images/专题-老乡镇/破镜.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img21',
    title: '稳定',
    desc: '',
    imageUrl: '/images/专题-老乡镇/稳定.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img22',
    title: '门',
    desc: '',
    imageUrl: '/images/专题-老乡镇/门.webp',
    category: null,
    project: 'old-towns',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img23',
    title: '下乡',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 .webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img24',
    title: '下乡 No.10',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.10.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img25',
    title: '下乡 No.11',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.11.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img26',
    title: '下乡 No.12',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.12.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img27',
    title: '下乡 No.13',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.13.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img28',
    title: '下乡 No.14',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.14.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img29',
    title: '下乡 No.15',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.15.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img30',
    title: '下乡 No.2',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.2.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img31',
    title: '下乡 No.3',
    desc: '图片来自吕兴丰',
    imageUrl: '/images/专题-途观/下乡 No.3.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img32',
    title: '下乡 No.4',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.4.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img33',
    title: '下乡 No.5',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.5.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img34',
    title: '下乡 No.6',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.6.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img35',
    title: '下乡 No.7',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.7.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img36',
    title: '下乡 No.8',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.8.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img37',
    title: '下乡 No.9',
    desc: '',
    imageUrl: '/images/专题-途观/下乡 No.9.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img38',
    title: '下乡',
    desc: '',
    imageUrl: '/images/专题-途观/下乡.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img39',
    title: '乡土',
    desc: '',
    imageUrl: '/images/专题-途观/乡土.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img40',
    title: '双向',
    desc: '',
    imageUrl: '/images/专题-途观/双向.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img41',
    title: '堆 No.2',
    desc: '',
    imageUrl: '/images/专题-途观/堆 No.2.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img42',
    title: '征服 No.2',
    desc: '',
    imageUrl: '/images/专题-途观/征服 No.2.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img43',
    title: '征服',
    desc: '',
    imageUrl: '/images/专题-途观/征服.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img44',
    title: '望向 No.2',
    desc: '',
    imageUrl: '/images/专题-途观/望向 No.2.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img45',
    title: '机器',
    desc: '',
    imageUrl: '/images/专题-途观/机器.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img46',
    title: '椒城 No.2',
    desc: '',
    imageUrl: '/images/专题-途观/椒城 No.2.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img47',
    title: '椒城 No.3',
    desc: '',
    imageUrl: '/images/专题-途观/椒城 No.3.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img48',
    title: '椒城 No.4',
    desc: '',
    imageUrl: '/images/专题-途观/椒城 No.4.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img49',
    title: '椒城 No.5',
    desc: '',
    imageUrl: '/images/专题-途观/椒城 No.5.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img50',
    title: '椒城',
    desc: '',
    imageUrl: '/images/专题-途观/椒城.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img51',
    title: '福&庆',
    desc: '',
    imageUrl: '/images/专题-途观/福&庆.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img52',
    title: '稻田',
    desc: '',
    imageUrl: '/images/专题-途观/稻田.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img53',
    title: '花椒',
    desc: '',
    imageUrl: '/images/专题-途观/花椒.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img54',
    title: '连接 No.4',
    desc: '',
    imageUrl: '/images/专题-途观/连接 No.4.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img55',
    title: '通道 No.7',
    desc: '',
    imageUrl: '/images/专题-途观/通道 No.7.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img56',
    title: '阳光&菊',
    desc: '',
    imageUrl: '/images/专题-途观/阳光&菊.webp',
    category: null,
    project: 'tu-guan',
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img57',
    title: '光音',
    desc: '',
    imageUrl: '/images/创意摄影/光音.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img58',
    title: '吉他特写',
    desc: '',
    imageUrl: '/images/创意摄影/吉他特写.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img59',
    title: '向光跑',
    desc: '',
    imageUrl: '/images/创意摄影/向光跑.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img60',
    title: '幻影',
    desc: '',
    imageUrl: '/images/创意摄影/幻影.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img61',
    title: '树型',
    desc: '',
    imageUrl: '/images/创意摄影/树型.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img62',
    title: '樱花重组',
    desc: '',
    imageUrl: '/images/创意摄影/樱花重组.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img63',
    title: '油花',
    desc: '',
    imageUrl: '/images/创意摄影/油花.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img64',
    title: '生机',
    desc: '',
    imageUrl: '/images/创意摄影/生机.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img65',
    title: '胭脂红 No.2',
    desc: '',
    imageUrl: '/images/创意摄影/胭脂红 No.2.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img66',
    title: '胭脂红',
    desc: '',
    imageUrl: '/images/创意摄影/胭脂红.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img67',
    title: '舞，跑',
    desc: '',
    imageUrl: '/images/创意摄影/舞，跑.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img68',
    title: '辉光',
    desc: '',
    imageUrl: '/images/创意摄影/辉光.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img69',
    title: '重构',
    desc: '',
    imageUrl: '/images/创意摄影/重构.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img70',
    title: '飞溅',
    desc: '',
    imageUrl: '/images/创意摄影/飞溅.webp',
    category: 'creative',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img71',
    title: '中线 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/中线 No.2.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img72',
    title: '中线',
    desc: '',
    imageUrl: '/images/新地形摄影/中线.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img73',
    title: '人，中心',
    desc: '',
    imageUrl: '/images/新地形摄影/人，中心.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img74',
    title: '假山',
    desc: '',
    imageUrl: '/images/新地形摄影/假山.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img75',
    title: '对数 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/对数 No.2.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img76',
    title: '对数',
    desc: '',
    imageUrl: '/images/新地形摄影/对数.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img77',
    title: '建',
    desc: '',
    imageUrl: '/images/新地形摄影/建 .webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img78',
    title: '建 No.4',
    desc: '',
    imageUrl: '/images/新地形摄影/建 No.4.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img79',
    title: '建',
    desc: '',
    imageUrl: '/images/新地形摄影/建.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img80',
    title: '扩张',
    desc: '',
    imageUrl: '/images/新地形摄影/扩张.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img81',
    title: '搁浅 (1)',
    desc: '',
    imageUrl: '/images/新地形摄影/搁浅 (1).webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img82',
    title: '曲线',
    desc: '',
    imageUrl: '/images/新地形摄影/曲线.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img83',
    title: '枯',
    desc: '',
    imageUrl: '/images/新地形摄影/枯.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img84',
    title: '江，桥，棚',
    desc: '',
    imageUrl: '/images/新地形摄影/江，桥，棚.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img85',
    title: '浅滩',
    desc: '',
    imageUrl: '/images/新地形摄影/浅滩.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img86',
    title: '田',
    desc: '',
    imageUrl: '/images/新地形摄影/田.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img87',
    title: '破墙而出',
    desc: '',
    imageUrl: '/images/新地形摄影/破墙而出.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img88',
    title: '童年 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/童年 No.2 .webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img89',
    title: '童年',
    desc: '',
    imageUrl: '/images/新地形摄影/童年.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img90',
    title: '绿皮草',
    desc: '',
    imageUrl: '/images/新地形摄影/绿皮草.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img91',
    title: '绿色围布',
    desc: '',
    imageUrl: '/images/新地形摄影/绿色围布.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img92',
    title: '虚构',
    desc: '',
    imageUrl: '/images/新地形摄影/虚构.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img93',
    title: '裂痕',
    desc: '',
    imageUrl: '/images/新地形摄影/裂痕.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img94',
    title: '谁高？',
    desc: '',
    imageUrl: '/images/新地形摄影/谁高？.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img95',
    title: '通道 No.2',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.2.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img96',
    title: '通道 No.3',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.3.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img97',
    title: '通道 No.4',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.4.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img98',
    title: '通道 No.5',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.5.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img99',
    title: '通道 No.6',
    desc: '',
    imageUrl: '/images/新地形摄影/通道 No.6.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img100',
    title: '通道',
    desc: '',
    imageUrl: '/images/新地形摄影/通道.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img101',
    title: '门',
    desc: '',
    imageUrl: '/images/新地形摄影/门.webp',
    category: 'new-topographics',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img102',
    title: '三角 No.3',
    desc: '',
    imageUrl: '/images/纪实摄影/三角 No.3.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img103',
    title: '农具 No.2',
    desc: '',
    imageUrl: '/images/纪实摄影/农具 No.2.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img104',
    title: '农具',
    desc: '',
    imageUrl: '/images/纪实摄影/农具.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img105',
    title: '劳作',
    desc: '',
    imageUrl: '/images/纪实摄影/劳作.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img106',
    title: '四宫格',
    desc: '',
    imageUrl: '/images/纪实摄影/四宫格.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img107',
    title: '堆',
    desc: '',
    imageUrl: '/images/纪实摄影/堆.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img108',
    title: '年后',
    desc: '',
    imageUrl: '/images/纪实摄影/年后.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img109',
    title: '延伸',
    desc: '',
    imageUrl: '/images/纪实摄影/延伸.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img110',
    title: '建 No.3',
    desc: '',
    imageUrl: '/images/纪实摄影/建 No.3.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img111',
    title: '影',
    desc: '',
    imageUrl: '/images/纪实摄影/影 .webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img112',
    title: '影 No.2',
    desc: '',
    imageUrl: '/images/纪实摄影/影 No.2.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img113',
    title: '戏水',
    desc: '',
    imageUrl: '/images/纪实摄影/戏水.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img114',
    title: '望向',
    desc: '',
    imageUrl: '/images/纪实摄影/望向.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img115',
    title: '灰烬',
    desc: '',
    imageUrl: '/images/纪实摄影/灰烬.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img116',
    title: '焦点',
    desc: '',
    imageUrl: '/images/纪实摄影/焦点.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img117',
    title: '狗脚印',
    desc: '',
    imageUrl: '/images/纪实摄影/狗脚印.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img118',
    title: '破裂',
    desc: '',
    imageUrl: '/images/纪实摄影/破裂.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img119',
    title: '破镜',
    desc: '',
    imageUrl: '/images/纪实摄影/破镜.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img120',
    title: '稳定',
    desc: '',
    imageUrl: '/images/纪实摄影/稳定.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img121',
    title: '等待',
    desc: '',
    imageUrl: '/images/纪实摄影/等待.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img122',
    title: '踏',
    desc: '',
    imageUrl: '/images/纪实摄影/踏.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img123',
    title: '车墙',
    desc: '',
    imageUrl: '/images/纪实摄影/车墙.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img124',
    title: '连接 No.2',
    desc: '',
    imageUrl: '/images/纪实摄影/连接 No.2.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img125',
    title: '连接 No.3',
    desc: '',
    imageUrl: '/images/纪实摄影/连接 No.3.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img126',
    title: '连接',
    desc: '',
    imageUrl: '/images/纪实摄影/连接.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img127',
    title: '遇见',
    desc: '',
    imageUrl: '/images/纪实摄影/遇见.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img128',
    title: '镜',
    desc: '',
    imageUrl: '/images/纪实摄影/镜.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img129',
    title: '阳光骑者',
    desc: '',
    imageUrl: '/images/纪实摄影/阳光骑者.webp',
    category: 'documentary',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img130',
    title: '三角 No.2',
    desc: '',
    imageUrl: '/images/静物摄影/三角 No.2.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img131',
    title: '三角 No.4',
    desc: '',
    imageUrl: '/images/静物摄影/三角 No.4.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img132',
    title: '三角',
    desc: '',
    imageUrl: '/images/静物摄影/三角.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img133',
    title: '单枝',
    desc: '',
    imageUrl: '/images/静物摄影/单枝.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img134',
    title: '向上',
    desc: '',
    imageUrl: '/images/静物摄影/向上.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img135',
    title: '多肉 No.2',
    desc: '',
    imageUrl: '/images/静物摄影/多肉 No.2.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img136',
    title: '多肉 No.3',
    desc: '',
    imageUrl: '/images/静物摄影/多肉 No.3.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img137',
    title: '多肉 No.4',
    desc: '',
    imageUrl: '/images/静物摄影/多肉 No.4.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img138',
    title: '多肉',
    desc: '',
    imageUrl: '/images/静物摄影/多肉.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img139',
    title: '干',
    desc: '',
    imageUrl: '/images/静物摄影/干.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img140',
    title: '春 No.2',
    desc: '',
    imageUrl: '/images/静物摄影/春 No.2.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img141',
    title: '春',
    desc: '',
    imageUrl: '/images/静物摄影/春.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img142',
    title: '枯',
    desc: '',
    imageUrl: '/images/静物摄影/枯 .webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img143',
    title: '树型 No.2A',
    desc: '',
    imageUrl: '/images/静物摄影/树型 No.2A.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img144',
    title: '树型 No.2B',
    desc: '',
    imageUrl: '/images/静物摄影/树型 No.2B.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img145',
    title: '洋桔梗',
    desc: '',
    imageUrl: '/images/静物摄影/洋桔梗.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img146',
    title: '空枝 No.2',
    desc: '',
    imageUrl: '/images/静物摄影/空枝 No.2.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img147',
    title: '空枝',
    desc: '',
    imageUrl: '/images/静物摄影/空枝.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img148',
    title: '绿草 No.2',
    desc: '',
    imageUrl: '/images/静物摄影/绿草 No.2.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img149',
    title: '绿草',
    desc: '',
    imageUrl: '/images/静物摄影/绿草.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img150',
    title: '花与蜜蜂',
    desc: '',
    imageUrl: '/images/静物摄影/花与蜜蜂.webp',
    category: 'still-life',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img151',
    title: '万家灯火',
    desc: '',
    imageUrl: '/images/风光摄影/万家灯火.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img152',
    title: '交织 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/交织 No.2.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img153',
    title: '交织',
    desc: '',
    imageUrl: '/images/风光摄影/交织.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img154',
    title: '加米峰 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/加米峰 No.2.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img155',
    title: '加米峰 No.3',
    desc: '',
    imageUrl: '/images/风光摄影/加米峰 No.3.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img156',
    title: '加米峰 No.4',
    desc: '',
    imageUrl: '/images/风光摄影/加米峰 No.4.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img157',
    title: '加米峰 No.5',
    desc: '',
    imageUrl: '/images/风光摄影/加米峰 No.5.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img158',
    title: '加米峰 No.6',
    desc: '',
    imageUrl: '/images/风光摄影/加米峰 No.6.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img159',
    title: '加米峰',
    desc: '',
    imageUrl: '/images/风光摄影/加米峰.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img160',
    title: '千厮门',
    desc: '',
    imageUrl: '/images/风光摄影/千厮门.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img161',
    title: '大礼堂',
    desc: '',
    imageUrl: '/images/风光摄影/大礼堂.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img162',
    title: '奔腾',
    desc: '',
    imageUrl: '/images/风光摄影/奔腾.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img163',
    title: '山间',
    desc: '',
    imageUrl: '/images/风光摄影/山间.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img164',
    title: '日照',
    desc: '',
    imageUrl: '/images/风光摄影/日照.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img165',
    title: '星',
    desc: '',
    imageUrl: '/images/风光摄影/星.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img166',
    title: '柴&山 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/柴&山 No.2.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img167',
    title: '柴&山',
    desc: '',
    imageUrl: '/images/风光摄影/柴&山.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img168',
    title: '江夜',
    desc: '',
    imageUrl: '/images/风光摄影/江夜.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img169',
    title: '群山之中',
    desc: '',
    imageUrl: '/images/风光摄影/群山之中.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img170',
    title: '菜园坝与夜',
    desc: '',
    imageUrl: '/images/风光摄影/菜园坝与夜.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img171',
    title: '蔡家大桥 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/蔡家大桥 No.2.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img172',
    title: '蔡家大桥 No.3',
    desc: '',
    imageUrl: '/images/风光摄影/蔡家大桥 No.3.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img173',
    title: '蔡家大桥',
    desc: '',
    imageUrl: '/images/风光摄影/蔡家大桥.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img174',
    title: '行者',
    desc: '',
    imageUrl: '/images/风光摄影/行者 .webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img175',
    title: '行者 No.2',
    desc: '',
    imageUrl: '/images/风光摄影/行者 No.2.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img176',
    title: '近草远桥',
    desc: '',
    imageUrl: '/images/风光摄影/近草远桥.webp',
    category: 'landscape',
    
    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img177',
    title: '霓虹',
    desc: '',
    imageUrl: '/images/风光摄影/霓虹.webp',
    category: 'landscape',

    location: '重庆',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/8 · 1/250s · ISO 400',
      focalLength: '35mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img178',
    title: '布置',
    desc: '',
    imageUrl: '/images/专题-碎隅光景/布置.webp',
    category: null,
    project: 'daily-moments',
    location: '日常',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/2.8 · 1/125s · ISO 800',
      focalLength: '50mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img179',
    title: '看',
    desc: '',
    imageUrl: '/images/专题-碎隅光景/看.webp',
    category: null,
    project: 'daily-moments',
    location: '日常',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/2.8 · 1/125s · ISO 800',
      focalLength: '50mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img180',
    title: '看 No.2',
    desc: '',
    imageUrl: '/images/专题-碎隅光景/看 No.2.webp',
    category: null,
    project: 'daily-moments',
    location: '日常',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/2.8 · 1/125s · ISO 800',
      focalLength: '50mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img181',
    title: '药',
    desc: '',
    imageUrl: '/images/专题-碎隅光景/药.webp',
    category: null,
    project: 'daily-moments',
    location: '日常',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/2.8 · 1/125s · ISO 800',
      focalLength: '50mm',
      format: '35mm Film',
    },
  },
  {
    id: 'img182',
    title: '重力',
    desc: '',
    imageUrl: '/images/专题-碎隅光景/重力.webp',
    category: null,
    project: 'daily-moments',
    location: '日常',
    year: 2024,
    aspectRatio: '3:2',
    exif: {
      camera: 'SONY ILCE-7M4',
      lens: 'FE 24-70mm F2.8 GM II',
      exposure: 'f/2.8 · 1/125s · ISO 800',
      focalLength: '50mm',
      format: '35mm Film',
    },
  },
];
import { Category, Project } from './types';

export type CategoryInfo = {
  nameZh: string;
  nameEn: string;
  desc: string;
};

export type ProjectInfo = {
  nameZh: string;
  nameEn: string;
  intro: string;
  background: string;
  duration: string;
};

export const CATEGORIES_INFO: Record<Category, CategoryInfo> = {
  landscape: {
    nameZh: '风光摄影',
    nameEn: 'Landscape Photography',
    desc: '山川河流、日出日落、自然之美',
  },
  documentary: {
    nameZh: '纪实摄影',
    nameEn: 'Documentary Photography',
    desc: '街头巷尾、人文故事、生活瞬间',
  },
  creative: {
    nameZh: '创意摄影',
    nameEn: 'Creative Photography',
    desc: '光影实验、艺术表达、视觉探索',
  },
  'new-topographics': {
    nameZh: '新地形摄影',
    nameEn: 'New Topographics',
    desc: '人与自然、城市边缘、环境变迁',
  },
  'still-life': {
    nameZh: '静物摄影',
    nameEn: 'Still Life Photography',
    desc: '静物、花卉、光影之美',
  },
};

export const PROJECTS_INFO: Record<Project, ProjectInfo> = {
  'old-towns': {
    nameZh: '老乡镇',
    nameEn: 'Old Towns',
    intro: '记录那些即将消失的老乡镇，留住时光的痕迹',
    background: '重庆老乡镇纪实摄影项目',
    duration: '2021 - 2024',
  },
  'new-villages': {
    nameZh: '新农村',
    nameEn: 'New Villages',
    intro: '新农村建设中的变化与传承',
    background: '重庆新农村发展记录',
    duration: '2023 - 2026',
  },
  'urban-borders': {
    nameZh: '城市边缘发展',
    nameEn: 'Urban Borders',
    intro: '城市扩张与乡村边界的交汇地带',
    background: '重庆城市化进程记录',
    duration: '2022 - 2026',
  },
  'tu-guan': {
    nameZh: '途观',
    nameEn: 'Tu Guan',
    intro: '路途中的观察与记录，行走在城乡之间',
    background: '沿途风光与人文纪实摄影项目',
    duration: '2023 - 2026',
  },
  'daily-moments': {
    nameZh: '碎隅光景',
    nameEn: 'Daily Moments',
    intro: '日常生活的点滴记录，捕捉平凡中的美好',
    background: '日常纪实摄影项目',
    duration: '2024 - 2026',
  },
  'living-diary': {
    nameZh: '生灵日记',
    nameEn: 'Living Diary',
    intro: '生命的故事，万物有灵',
    background: '动物与自然生态摄影项目',
    duration: '2024 - 2026',
  },
};

// 视频分类信息
export const VIDEO_CATEGORIES_INFO: Record<VideoCategory, VideoCategoryDetails> = {
  'behind-the-scenes': {
    id: VideoCategory.BehindTheScenes,
    nameZh: '幕后花絮',
    nameEn: 'Behind the Scenes',
    description: '摄影创作的幕后故事',
  },
  'creative-process': {
    id: VideoCategory.CreativeProcess,
    nameZh: '创作过程',
    nameEn: 'Creative Process',
    description: '从构思到成片的完整记录',
  },
  'documentary': {
    id: VideoCategory.Documentary,
    nameZh: '纪录片',
    nameEn: 'Documentary',
    description: '实地考察与项目纪录',
  },
  'tutorial': {
    id: VideoCategory.Tutorial,
    nameZh: '教程',
    nameEn: 'Tutorial',
    description: '摄影技巧与后期分享',
  },
  'other': {
    id: VideoCategory.Other,
    nameZh: '其他',
    nameEn: 'Other',
    description: '其他视频内容',
  },
};

// 视频数据
export const VIDEOS: Video[] = [
  {
    id: 'video-001',
    title: '《临界点&城市边缘》城市在长，农田在退',
    titleEn: 'Critical Point & Urban Edges',
    description: '探索城市扩张与农田退让的边界地带，记录快速城市化进程中的土地变迁与人文思考。',
    category: VideoCategory.Documentary,
    bvid: 'BV1bM596qEoA', // 从 https://b23.tv/EBul8Ub 提取
    coverUrl: '/images/新地形摄影/虚构.webp', // 视频预览封面
    duration: '待补充',
    uploadDate: '2025-01',
    project: Project.UrbanBorders,
    tags: ['城市边缘', '纪实摄影', '重庆'],
  },
];
